version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.4-alpine
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    container_name: foodgram-back
    image: annatsoy/foodgram_backend:latest
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media
  frontend:
    container_name: foodgram-front
    image: annatsoy/foodgram_frontend:latest
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: annatsoy/foodgram_gateway
    env_file: ./.env
    depends_on:
      - frontend
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media
