# Generated by Django 3.2.3 on 2024-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='Рецепт уже есть в избранном',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='Рецепт уже есть в списке покупок',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(blank=True, max_length=70),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже есть в избранном'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже есть в списке покупок'),
        ),
    ]
