# Generated by Django 3.2.3 on 2024-09-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20240907_1704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="short_link",
        ),
    ]
