# Generated by Django 3.2.3 on 2024-06-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240612_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'ordering': ('ingredient',), 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
    ]
