# Generated by Django 3.2.3 on 2024-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(blank=True, max_length=70),
        ),
    ]
