# Generated by Django 3.2.3 on 2024-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientsamount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
