# Generated by Django 3.2.3 on 2024-09-15 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_short_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='Рецепт уже есть в списке покупок',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не менее 1 минут'), django.core.validators.MaxValueValidator(32000, 'Время приготовления не дольше 32000 минут')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже в списке покупок'),
        ),
    ]
