# Generated by Django 3.2.3 on 2024-09-21 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240915_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не менее 1 минут'), django.core.validators.MaxValueValidator(32000, 'Время приготовления не дольше 32000 минут')], verbose_name='Время приготовления в минутах.'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть не меньше 1'), django.core.validators.MaxValueValidator(30000, 'Значение должно быть не больше 30000')], verbose_name='Количество ингредиента'),
        ),
    ]
