# Generated by Django 3.2.3 on 2024-09-07 17:04

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Такая подписка уже есть',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нет смысла в подписке на себя',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date_added',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='Такая подписка уже есть'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='Нет смысла в подписке на себя'),
        ),
    ]
