# Generated by Django 3.2.3 on 2024-09-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240907_1704'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Такая подписка уже есть',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Такая подписка уже есть'),
        ),
    ]
