# Generated by Django 3.2.3 on 2024-09-21 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240908_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя должно состоять только из букв', regex='^[a-zA-Zа-яА-Я\\s]*$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='В фамилии могут быть только буквы пробелы и тире', regex='^[a-zA-Zа-яА-Я\\s\\-]*$')], verbose_name='Фамилия'),
        ),
    ]
