# Generated by Django 3.2.3 on 2024-06-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
