# Generated by Django 3.2.3 on 2024-06-18 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Подписался'),
            preserve_default=False,
        ),
    ]
